# javaland-2022-karate-workshop

Sample application and code for Testing mit Karate at Javaland 2022

## Resources

Karate is a DSL for Testautomation. A comprehensive documentation can be found here:

https://karatelabs.github.io/karate/


Karate Mock is a feature to write API mocks using the same language as you use for API testing.

https://karatelabs.github.io/karate/karate-netty/


Karate UI Test:

https://karatelabs.github.io/karate/karate-core/#karate-ui

## Start Application

This application requires a postgresql database.

Simply execute the following docker command:

[source, bash]
----
$ docker-compose -f docker/postgres.yml up -d
----

Visit the application on http://localhost:8080 after startup.

The Swagger Doc can be seen on http://localhost:8080/swagger-ui/index.html


## Architecture

[plantuml, target=diagram-classes, format=png]
----
AdminApi - [Duell Application]
WEB - [Duell Application]
[Duell Application] ..> JDBC : postgres
[Duell Application] ..> HTTP : los-schimpfos.de/schimpfos-wortos.php
----

## Start Testing

The `com.github.atomfrede.javaland.beleidigungsduell.integation.StartTestEnv`
class can be used to start the application in "Test-Mode".

Test mode means that a PostgresSQL is started with testcontainers and
the Los Schimpfos API is replaced by a Karate Mock implementation.

This enables you to execute your integration test fast and reliable,
because this is the same setup used when running integration test.

## Follow Us

* https://twitter.com/peter_quiel[@peter_quiel]
* https://twitter.com/atomfrede[@atomfrede]
* https://twitter.com/jugpaderborn[@jugpaderborn]


