CREATE
    TABLE
        beleidigung(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
            beleidigungs_id UUID NOT NULL DEFAULT gen_random_uuid (),
            antwort_id UUID NOT NULL DEFAULT gen_random_uuid (),
            beleidigungs_template CHARACTER VARYING NOT NULL ,
            antwort_template CHARACTER VARYING NOT NULL ,

            PRIMARY KEY(
                id
            )
        );


